/**
 * Mock data store — used when Firebase env vars are placeholders.
 * All data lives in memory; writes update these arrays for the session.
 */

import {
  RegistrationConfig, UserProfile, StudioEvent, DanceClass,
  Coupon, Order, ClassEnrollment, FacultyProfile, AttendanceRecord,
  EventRegistration, SiteVideo,
} from '../types'

// ── Helpers ──────────────────────────────────────────────────────────────────

export const MOCK_MODE =
  typeof process !== 'undefined' &&
  (process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID === 'placeholder' ||
   !process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID)

function ts(date: Date = new Date()): any {
  return { seconds: Math.floor(date.getTime() / 1000), nanoseconds: 0, toDate: () => date }
}
function daysAgo(n: number) { const d = new Date(); d.setDate(d.getDate() - n); return d }
function daysFromNow(n: number) { const d = new Date(); d.setDate(d.getDate() + n); return d }
function monthsFromNow(n: number) { const d = new Date(); d.setMonth(d.getMonth() + n); return d }

let _id = 1
function uid() { return `mock-${_id++}` }

// ── Registration Config ───────────────────────────────────────────────────────

export const mockConfig: RegistrationConfig = {
  amount: 2000,
  validityMonths: 12,
  pauseAmount: 500,
  pauseValidityMonths: 2,
  updatedAt: ts(),
}

// ── Users / Students ──────────────────────────────────────────────────────────

export const mockUsers: UserProfile[] = [
  {
    uid: 'mock-admin',
    displayName: 'Admin',
    email: 'admin@mock.local',
    role: 'admin',
    registrationStatus: 'active',
    profileComplete: true,
    linkedEmails: ['admin@mock.local'],
    linkedPhones: [],
    enrolledClasses: [],
    bookings: [],
    createdAt: ts(daysAgo(90)),
    updatedAt: ts(),
  },
  {
    uid: 'mock-user',
    displayName: 'Student User',
    email: 'user@mock.local',
    role: 'user',
    registrationStatus: 'active',
    profileComplete: true,
    gender: 'male',
    phone: '+919830000001',
    dob: '1998-05-15',
    yearsOfDancing: 2,
    registrationExpiry: ts(monthsFromNow(10)),
    linkedEmails: ['user@mock.local'],
    linkedPhones: ['+919830000001'],
    enrolledClasses: ['class-1', 'class-3'],
    bookings: [],
    createdAt: ts(daysAgo(60)),
    updatedAt: ts(),
  },
  {
    uid: 'mock-crew',
    displayName: 'Crew Member',
    email: 'crew@mock.local',
    role: 'faculty',
    registrationStatus: 'active',
    profileComplete: true,
    linkedEmails: ['crew@mock.local'],
    linkedPhones: [],
    enrolledClasses: [],
    bookings: [],
    createdAt: ts(daysAgo(80)),
    updatedAt: ts(),
  },
  {
    uid: 'student-priya',
    displayName: 'Priya Sharma',
    email: 'priya.sharma@gmail.com',
    phone: '+919830158001',
    role: 'user',
    gender: 'female',
    dob: '2000-03-22',
    yearsOfDancing: 0,
    registrationStatus: 'pending_approval',
    profileComplete: true,
    linkedEmails: ['priya.sharma@gmail.com'],
    linkedPhones: ['+919830158001'],
    enrolledClasses: [],
    bookings: [],
    createdAt: ts(daysAgo(3)),
    updatedAt: ts(),
  },
  {
    uid: 'student-rahul',
    displayName: 'Rahul Verma',
    email: 'rahul.verma@outlook.com',
    phone: '+919830158002',
    role: 'user',
    gender: 'male',
    dob: '1995-11-08',
    yearsOfDancing: 3,
    registrationStatus: 'active',
    registrationExpiry: ts(monthsFromNow(8)),
    profileComplete: true,
    linkedEmails: ['rahul.verma@outlook.com'],
    linkedPhones: ['+919830158002'],
    enrolledClasses: ['class-2'],
    bookings: [],
    createdAt: ts(daysAgo(45)),
    updatedAt: ts(),
  },
  {
    uid: 'student-ananya',
    displayName: 'Ananya Bose',
    email: 'ananya.bose@gmail.com',
    phone: '+919830158003',
    role: 'user',
    gender: 'female',
    dob: '2002-07-17',
    yearsOfDancing: 1,
    registrationStatus: 'pending_approval',
    profileComplete: true,
    linkedEmails: ['ananya.bose@gmail.com'],
    linkedPhones: ['+919830158003'],
    enrolledClasses: [],
    bookings: [],
    createdAt: ts(daysAgo(1)),
    updatedAt: ts(),
  },
  {
    uid: 'student-kunal',
    displayName: 'Kunal Das',
    email: 'kunal.das@yahoo.com',
    phone: '+919830158004',
    role: 'user',
    gender: 'male',
    dob: '1993-09-30',
    yearsOfDancing: 5,
    registrationStatus: 'expired',
    profileComplete: true,
    linkedEmails: ['kunal.das@yahoo.com'],
    linkedPhones: ['+919830158004'],
    enrolledClasses: [],
    bookings: [],
    createdAt: ts(daysAgo(400)),
    updatedAt: ts(daysAgo(5)),
  },
]

// ── Faculty Profiles ──────────────────────────────────────────────────────────

export const mockFaculty: FacultyProfile[] = [
  {
    id: 'faculty-hitesh',
    uid: 'mock-crew',
    name: 'Hitesh H. Teckchandani',
    email: 'hitesh@salsawalastudios.com',
    phone: '+919830158220',
    role: 'faculty',
    assignedClasses: ['class-1', 'class-2', 'class-7'],
    assignedEvents: ['event-1', 'event-3'],
    active: true,
    createdAt: ts(daysAgo(365)),
  },
  {
    id: 'faculty-priyam',
    name: 'Priyam Bose',
    email: 'priyam@salsawalastudios.com',
    phone: '+919830158221',
    role: 'faculty',
    assignedClasses: ['class-4', 'class-6', 'class-8'],
    assignedEvents: ['event-2'],
    active: true,
    createdAt: ts(daysAgo(300)),
  },
  {
    id: 'faculty-akash',
    name: 'Akash Agarwal',
    email: 'akash@salsawalastudios.com',
    phone: '+919830158222',
    role: 'crew',
    assignedClasses: ['class-3', 'class-9'],
    assignedEvents: [],
    active: true,
    createdAt: ts(daysAgo(200)),
  },
]

// ── Classes (DanceClass format) ───────────────────────────────────────────────

export const mockClasses: DanceClass[] = [
  {
    id: 'class-1',
    name: 'Salsa Beginners',
    description: 'Perfect entry point into Latin dance. Learn basic steps, timing and partner work.',
    style: 'Salsa',
    level: 'Beginner',
    days: ['Mon'],
    timeFrom: '19:00',
    timeTo: '20:00',
    maxDurationMonths: 6,
    pricePerMonth: 3200,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-hitesh'],
    active: true,
    createdAt: ts(daysAgo(90)),
    updatedAt: ts(),
  },
  {
    id: 'class-2',
    name: 'Bachata — All Levels',
    description: 'Sensual rhythms, body movement and connection. All levels welcome.',
    style: 'Bachata',
    level: 'All Levels',
    days: ['Tue'],
    timeFrom: '19:00',
    timeTo: '20:00',
    maxDurationMonths: 6,
    pricePerMonth: 3200,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-hitesh'],
    active: true,
    createdAt: ts(daysAgo(90)),
    updatedAt: ts(),
  },
  {
    id: 'class-3',
    name: 'Hip-Hop Street',
    description: 'Raw energy, freestyle and street style. Express yourself.',
    style: 'Hip-Hop',
    level: 'Beginner',
    days: ['Wed'],
    timeFrom: '18:00',
    timeTo: '19:15',
    maxDurationMonths: 3,
    pricePerMonth: 2800,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-akash'],
    active: true,
    createdAt: ts(daysAgo(80)),
    updatedAt: ts(),
  },
  {
    id: 'class-4',
    name: 'Contemporary Dance',
    description: 'Fluid, expressive, emotional. Push your creative boundaries.',
    style: 'Contemporary',
    level: 'All Levels',
    days: ['Wed'],
    timeFrom: '19:30',
    timeTo: '20:30',
    maxDurationMonths: 6,
    pricePerMonth: 3000,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-priyam'],
    active: true,
    createdAt: ts(daysAgo(80)),
    updatedAt: ts(),
  },
  {
    id: 'class-5',
    name: 'Salsa Intermediate',
    description: 'Build on the basics — shines, combinations and more.',
    style: 'Salsa',
    level: 'Intermediate',
    days: ['Thu'],
    timeFrom: '19:00',
    timeTo: '20:00',
    maxDurationMonths: 6,
    pricePerMonth: 3600,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-hitesh'],
    active: true,
    createdAt: ts(daysAgo(75)),
    updatedAt: ts(),
  },
  {
    id: 'class-6',
    name: 'Bollywood Dance',
    description: 'Vibrant, energetic, cinematic. Bring Bollywood to life.',
    style: 'Bollywood',
    level: 'All Levels',
    days: ['Thu'],
    timeFrom: '17:30',
    timeTo: '18:30',
    maxDurationMonths: 3,
    pricePerMonth: 2800,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-priyam'],
    active: true,
    createdAt: ts(daysAgo(70)),
    updatedAt: ts(),
  },
  {
    id: 'class-7',
    name: 'Kizomba — All Levels',
    description: 'African elegance, smooth connection, deep musicality.',
    style: 'Kizomba',
    level: 'All Levels',
    days: ['Fri'],
    timeFrom: '20:00',
    timeTo: '21:15',
    maxDurationMonths: 6,
    pricePerMonth: 3600,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-hitesh'],
    active: true,
    createdAt: ts(daysAgo(65)),
    updatedAt: ts(),
  },
  {
    id: 'class-8',
    name: 'Pilates for Dancers',
    description: 'Core strength, flexibility and posture — every dancer needs this.',
    style: 'Pilates',
    level: 'All Levels',
    days: ['Sat'],
    timeFrom: '09:00',
    timeTo: '10:00',
    maxDurationMonths: 3,
    pricePerMonth: 2800,
    classesPerMonth: 4,
    assignedFaculty: ['faculty-priyam'],
    active: true,
    createdAt: ts(daysAgo(60)),
    updatedAt: ts(),
  },
]

// ── Events ────────────────────────────────────────────────────────────────────

export const mockEvents: StudioEvent[] = [
  {
    id: 'event-1',
    title: 'Salsa & Bachata Social Night',
    description: 'Join us for a fun evening of social dancing! All levels welcome. DJ set, open floor, and mini-performance by our faculty.',
    date: daysFromNow(12).toISOString().split('T')[0],
    time: '7:00 PM – 11:00 PM',
    venue: 'Salsawala Studios, Park Street, Kolkata',
    price: 500,
    capacity: 80,
    enrolled: 34,
    type: 'social',
    tag: 'Social Night',
    gradient: 'from-red-500 to-rose-400',
    assignedFaculty: ['faculty-hitesh'],
    active: true,
    createdAt: ts(daysAgo(20)),
  },
  {
    id: 'event-2',
    title: 'Contemporary Dance Workshop',
    description: 'An intensive 3-hour workshop with Priyam Bose. Explore body movement, floor work and improvisation. Beginners welcome.',
    date: daysFromNow(25).toISOString().split('T')[0],
    time: '10:00 AM – 1:00 PM',
    venue: 'Salsawala Studios, Park Street, Kolkata',
    price: 1200,
    capacity: 25,
    enrolled: 18,
    type: 'workshop',
    tag: 'Workshop',
    gradient: 'from-teal-500 to-emerald-400',
    assignedFaculty: ['faculty-priyam'],
    active: true,
    createdAt: ts(daysAgo(15)),
  },
  {
    id: 'event-3',
    title: 'Monsoon Salsa Festival 2026',
    description: 'Kolkata\'s biggest Salsa event! 3 rooms, 5 DJs, international guest performers, workshops all day. Early bird discount available.',
    date: daysFromNow(45).toISOString().split('T')[0],
    time: '5:00 PM – 2:00 AM',
    venue: 'The Grand Ballroom, Park Hotel, Kolkata',
    price: 1800,
    capacity: 300,
    enrolled: 127,
    type: 'competition',
    tag: 'Festival',
    gradient: 'from-purple-600 to-indigo-500',
    assignedFaculty: ['faculty-hitesh', 'faculty-priyam'],
    active: true,
    createdAt: ts(daysAgo(10)),
  },
  {
    id: 'event-4',
    title: 'Bollywood Dance Performance Night',
    description: 'Showcasing our students in a live performance. Come cheer for our dancers and enjoy a spectacular Bollywood evening.',
    date: daysFromNow(60).toISOString().split('T')[0],
    time: '6:00 PM – 9:00 PM',
    venue: 'Rabindra Sadan, Kolkata',
    price: 800,
    capacity: 200,
    enrolled: 45,
    type: 'performance',
    tag: 'Performance',
    gradient: 'from-yellow-500 to-orange-400',
    assignedFaculty: ['faculty-priyam', 'faculty-akash'],
    active: true,
    createdAt: ts(daysAgo(5)),
  },
]

// ── Coupons ───────────────────────────────────────────────────────────────────

export const mockCoupons: Coupon[] = [
  {
    id: 'coupon-1',
    code: 'WELCOME500',
    type: 'flat',
    value: 500,
    appliesTo: 'all_classes',
    usagePerUser: 1,
    totalUsed: 12,
    usedBy: {},
    active: true,
    createdAt: ts(daysAgo(60)),
  },
  {
    id: 'coupon-2',
    code: 'FEST20',
    type: 'percent',
    value: 20,
    maxDiscount: 1000,
    appliesTo: 'specific_event',
    targetId: 'event-3',
    usagePerUser: 1,
    totalUsed: 30,
    usedBy: {},
    active: true,
    createdAt: ts(daysAgo(10)),
  },
]

// ── Orders (pending cash) ─────────────────────────────────────────────────────

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    userId: 'student-priya',
    userName: 'Priya Sharma',
    userEmail: 'priya.sharma@gmail.com',
    userPhone: '+919830158001',
    items: [{ type: 'registration', id: 'registration', name: 'Studio Registration', pricePerUnit: 2000, quantity: 1 }],
    subtotal: 2000,
    discountAmount: 0,
    totalAmount: 2000,
    paymentMethod: 'cash',
    paymentStatus: 'pending',
    createdAt: ts(daysAgo(3)),
  },
  {
    id: 'order-2',
    userId: 'student-ananya',
    userName: 'Ananya Bose',
    userEmail: 'ananya.bose@gmail.com',
    userPhone: '+919830158003',
    items: [{ type: 'registration', id: 'registration', name: 'Studio Registration', pricePerUnit: 2000, quantity: 1 }],
    subtotal: 2000,
    discountAmount: 0,
    totalAmount: 2000,
    paymentMethod: 'cash',
    paymentStatus: 'pending',
    createdAt: ts(daysAgo(1)),
  },
  {
    id: 'order-3',
    userId: 'student-rahul',
    userName: 'Rahul Verma',
    userEmail: 'rahul.verma@outlook.com',
    items: [
      { type: 'class', id: 'class-2', name: 'Bachata — All Levels', pricePerUnit: 3200, durationMonths: 3, quantity: 1 },
    ],
    subtotal: 9600,
    discountAmount: 500,
    couponCode: 'WELCOME500',
    totalAmount: 9100,
    paymentMethod: 'cash',
    paymentStatus: 'pending',
    createdAt: ts(daysAgo(2)),
  },
]

// ── Enrollments (for mock-user) ───────────────────────────────────────────────

export const mockEnrollments: ClassEnrollment[] = [
  {
    id: 'enr-1',
    userId: 'mock-user',
    classId: 'class-1',
    className: 'Salsa Beginners',
    durationMonths: 3,
    startDate: ts(daysAgo(30)),
    endDate: ts(daysFromNow(60)),
    status: 'active',
    orderId: 'order-mock-1',
    createdAt: ts(daysAgo(30)),
  },
  {
    id: 'enr-2',
    userId: 'mock-user',
    classId: 'class-3',
    className: 'Hip-Hop Street',
    durationMonths: 2,
    startDate: ts(daysAgo(15)),
    endDate: ts(daysFromNow(45)),
    status: 'active',
    orderId: 'order-mock-2',
    createdAt: ts(daysAgo(15)),
  },
  {
    id: 'enr-3',
    userId: 'student-rahul',
    classId: 'class-2',
    className: 'Bachata — All Levels',
    durationMonths: 3,
    startDate: ts(daysAgo(10)),
    endDate: ts(daysFromNow(80)),
    status: 'active',
    orderId: 'order-3',
    createdAt: ts(daysAgo(10)),
  },
]

// ── Event Registrations ───────────────────────────────────────────────────────

export const mockEventRegistrations: EventRegistration[] = [
  {
    id: 'ereg-1',
    userId: 'mock-user',
    eventId: 'event-3',
    eventTitle: 'Monsoon Salsa Festival 2026',
    name: 'Student User',
    email: 'user@mock.local',
    gender: 'male',
    source: 'Instagram',
    paymentStatus: 'confirmed',
    paymentMethod: 'online',
    amount: 1800,
    createdAt: ts(daysAgo(5)),
  },
]

// ── In-memory mutable store ───────────────────────────────────────────────────
// Allows writes during the test session (resets on page reload)

export const store = {
  config: { ...mockConfig },
  users: [...mockUsers],
  faculty: [...mockFaculty],
  classes: [...mockClasses],
  events: [...mockEvents],
  coupons: [...mockCoupons],
  orders: [...mockOrders],
  enrollments: [...mockEnrollments],
  eventRegistrations: [...mockEventRegistrations],
  videos: [] as any[],
  attendance: [] as AttendanceRecord[],
}

export function genId() {
  return `mock-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
}
